################################################################################
# Automatically-generated file. Do not edit!
################################################################################

O_SRCS := 
CPP_SRCS := 
K_SRCS := 
LD_SRCS := 
S67_SRCS := 
LDS_SRCS := 
CMD_SRCS := 
EXE_SRCS := 
CXX_SRCS := 
CMD_UPPER_SRCS := 
ELF_SRCS := 
C43_SRCS := 
S55_SRCS := 
LD_UPPER_SRCS := 
C62_SRCS := 
S_UPPER_SRCS := 
A_SRCS := 
C55_SRCS := 
SA_SRCS := 
LDS_UPPER_SRCS := 
C_UPPER_SRCS := 
OUT_SRCS := 
OBJ_SRCS := 
S62_SRCS := 
LIB_SRCS := 
ASM_SRCS := 
S??_SRCS := 
C++_SRCS := 
CLA_SRCS := 
ASM_UPPER_SRCS := 
C_SRCS := 
C67_SRCS := 
S_SRCS := 
S43_SRCS := 
OPT_SRCS := 
C64_SRCS := 
C??_SRCS := 
CC_SRCS := 
S64_SRCS := 
OBJS := 
BIN_OUTPUTS := 
S_DEPS := 
S_UPPER_DEPS := 
S62_DEPS := 
C64_DEPS := 
ASM_DEPS := 
CC_DEPS := 
S55_DEPS := 
C67_DEPS := 
C??_DEPS := 
CLA_DEPS := 
CPP_DEPS := 
S??_DEPS := 
C_DEPS := 
C62_DEPS := 
EXE_OUTPUTS := 
CXX_DEPS := 
C++_DEPS := 
ASM_UPPER_DEPS := 
K_DEPS := 
C43_DEPS := 
S67_DEPS := 
SA_DEPS := 
S43_DEPS := 
OPT_DEPS := 
S64_DEPS := 
C_UPPER_DEPS := 
C55_DEPS := 
CPP_DEPS__QUOTED := 
C67_DEPS__QUOTED := 
C??_DEPS__QUOTED := 
S_UPPER_DEPS__QUOTED := 
CLA_DEPS__QUOTED := 
ASM_UPPER_DEPS__QUOTED := 
C62_DEPS__QUOTED := 
CXX_DEPS__QUOTED := 
EXE_OUTPUTS__QUOTED := 
S67_DEPS__QUOTED := 
BIN_OUTPUTS__QUOTED := 
C_DEPS__QUOTED := 
C_UPPER_DEPS__QUOTED := 
OPT_DEPS__QUOTED := 
S_DEPS__QUOTED := 
S??_DEPS__QUOTED := 
K_DEPS__QUOTED := 
C64_DEPS__QUOTED := 
C++_DEPS__QUOTED := 
OBJS__QUOTED := 
S43_DEPS__QUOTED := 
CC_DEPS__QUOTED := 
S55_DEPS__QUOTED := 
C55_DEPS__QUOTED := 
SA_DEPS__QUOTED := 
C43_DEPS__QUOTED := 
S62_DEPS__QUOTED := 
ASM_DEPS__QUOTED := 
S64_DEPS__QUOTED := 

# Every subdirectory with source files must be described here
SUBDIRS := \
projects/xpressohack/OpenWSN_OS/src \
projects/xpressohack/OpenWSN_OS/src/OpenAL \
projects/xpressohack/OpenWSN_OS/src/OpenAL/internal \
projects/xpressohack/01bsp_timers/application \
projects/xpressohack/01bsp_spi/application \
projects/xpressohack/01bsp_radio/application \
projects/xpressohack/01bsp_leds/application \
projects/xpressohack/00std_spi/src \
projects/xpressohack/00std_eui64b/src \
projects/wsn430v14/00std_uart \
projects/wsn430v14/00std_spi \
projects/wsn430v14/00std_leds_xtal \
projects/wsn430v14/00std_eui64 \
projects/wsn430v14/00std_clocks \
projects/wsn430v13b/00std_uart \
projects/wsn430v13b/00std_spi \
projects/wsn430v13b/00std_leds_xtal \
projects/wsn430v13b/00std_i2c \
projects/wsn430v13b/00std_eui64 \
projects/wsn430v13b/00std_clocks \
projects/wsn430v13b/00std_button \
projects/telosb/00std_uart0 \
projects/telosb/00std_uart \
projects/telosb/00std_spi \
projects/telosb/00std_leds_xtal \
projects/telosb/00std_i2c \
projects/telosb/00std_eui64 \
projects/telosb/00std_clocks \
projects/telosb/00std_chromatic \
projects/telosb/00std_button \
projects/samr21_xpro/03oos_openwsn/cmsis/src \
projects/samr21_xpro/03oos_openwsn/cmsis/linkerScripts \
projects/samr21_xpro/03oos_macpong/cmsis/src \
projects/samr21_xpro/03oos_macpong/cmsis/linkerScripts \
projects/samr21_xpro/02drv_opentimers/cmsis/src \
projects/samr21_xpro/02drv_opentimers/cmsis/linkerScripts \
projects/samr21_xpro/01bsp_uart/cmsis/src \
projects/samr21_xpro/01bsp_uart/cmsis/linkerScripts \
projects/samr21_xpro/01bsp_timer/cmsis/src \
projects/samr21_xpro/01bsp_timer/cmsis/linkerScripts \
projects/samr21_xpro/01bsp_spi/cmsis/src \
projects/samr21_xpro/01bsp_spi/cmsis/linkerScripts \
projects/samr21_xpro/01bsp_radiotimer/cmsis/src \
projects/samr21_xpro/01bsp_radiotimer/cmsis/linkerScripts \
projects/samr21_xpro/01bsp_radio_tx/cmsis/src \
projects/samr21_xpro/01bsp_radio_tx/cmsis/linkerScripts \
projects/samr21_xpro/01bsp_radio_rx/cmsis/src \
projects/samr21_xpro/01bsp_radio_rx/cmsis/linkerScripts \
projects/samr21_xpro/01bsp_radio/cmsis/src \
projects/samr21_xpro/01bsp_radio/cmsis/linkerScripts \
projects/samr21_xpro/01bsp_leds/cmsis/src \
projects/samr21_xpro/01bsp_leds/cmsis/linkerScripts \
projects/samr21_xpro/01bsp_flash/cmsis/src \
projects/samr21_xpro/01bsp_flash/cmsis/linkerScripts \
projects/samr21_xpro/01bsp_flash \
projects/samr21_xpro/01bsp_closetimers/cmsis/src \
projects/samr21_xpro/01bsp_closetimers/cmsis/linkerScripts \
projects/samr21_xpro/01bsp_bothtimers/cmsis/src \
projects/samr21_xpro/01bsp_bothtimers/cmsis/linkerScripts \
projects/samr21_xpro/00std_low_power_mode \
projects/samr21_xpro/00std_low_power_mode/cmsis/src \
projects/samr21_xpro/00std_low_power_mode/cmsis/linkerScripts \
projects/openmotestm/01bsp_flash/application \
projects/openmotestm/00std_low_power_mode \
projects/gina/old \
projects/gina/02drv_headsup \
projects/gina/00std_uart \
projects/gina/00std_timers \
projects/gina/00std_leds_xtal \
projects/gina/00std_eui64 \
projects/common \
projects/common/03oos_openwsn \
projects/common/03oos_mercator \
projects/common/03oos_macpong \
projects/common/02drv_opentimers \
projects/common/02drv_openserial \
projects/common/01bsp_uart \
projects/common/01bsp_spi \
projects/common/01bsp_radiotimer \
projects/common/01bsp_radio_tx \
projects/common/01bsp_radio_rx \
projects/common/01bsp_radio \
projects/common/01bsp_leds \
projects/common/01bsp_debugpins \
projects/common/01bsp_closetimers \
projects/common/01bsp_bsp_timer \
projects/common/01bsp_bothtimers \
projects/agilefox/01bsp_flash/application \
projects/agilefox/00std_low_power_mode \
openstack \
openstack/cross-layers \
openstack/04-TRAN \
openstack/03b-IPv6 \
openstack/03a-IPHC \
openstack/02b-MAChigh \
openstack/02a-MAClow \
openapps/uecho \
openapps/tohlone \
openapps/techo \
openapps/rrt \
openapps/osens \
openapps \
openapps/cwellknown \
openapps/cstorm \
openapps/cleds \
openapps/cinfo \
openapps/cexample \
openapps/c6t \
kernel/openos \
kernel/freertos \
kernel/freertos/FreeRTOSV8.1.2/FreeRTOS/Source \
kernel/freertos/FreeRTOSV8.1.2/FreeRTOS/Source/portable/MemMang \
kernel/freertos/FreeRTOSV8.1.2/FreeRTOS/Source/portable/IAR/MSP430 \
kernel/freertos/FreeRTOSV8.1.2/FreeRTOS/Source/portable/IAR/ARM_CM4F \
kernel/freertos/FreeRTOSV8.1.2/FreeRTOS/Source/portable/IAR/ARM_CM3 \
kernel/freertos/FreeRTOSV8.1.2/FreeRTOS/Source/portable/GCC/MSP430F449 \
kernel/freertos/FreeRTOSV8.1.2/FreeRTOS/Source/portable/GCC/ARM_CM4F \
kernel/freertos/FreeRTOSV8.1.2/FreeRTOS/Source/portable/GCC/ARM_CM3 \
drivers/z1 \
drivers/gina \
drivers/common \
drivers/OpenMote-CC2538 \
bsp/chips/cc2420 \
bsp/chips/cc1101 \
bsp/chips/at86rf233 \
bsp/chips/at86rf231 \
bsp/boards/z1 \
bsp/boards/xpressohack \
bsp/boards/wsn430v14 \
bsp/boards/wsn430v13b \
bsp/boards/telosb \
bsp/boards/samr21_xpro \
bsp/boards/samr21_xpro/drivers/src \
bsp/boards/python \
bsp/boards/openmotestm \
bsp/boards/openmotestm/library/src \
bsp/boards/openmotestm/ewarm \
bsp/boards/openmotestm/configure \
bsp/boards/k20/cpu \
bsp/boards/k20/common \
bsp/boards/k20/bsp_ext \
bsp/boards/k20/bsp \
bsp/boards/iot-lab_M3 \
bsp/boards/iot-lab_M3/library/STM32F10x_StdPeriph_Lib_V3.5.0/Libraries/STM32F10x_StdPeriph_Driver/src \
bsp/boards/iot-lab_M3/library/STM32F10x_StdPeriph_Lib_V3.5.0/Libraries/CMSIS/CM3/DeviceSupport/ST/STM32F10x \
bsp/boards/iot-lab_M3/library/STM32F10x_StdPeriph_Lib_V3.5.0/Libraries/CMSIS/CM3/DeviceSupport/ST/STM32F10x/startup/iar \
bsp/boards/iot-lab_M3/library/STM32F10x_StdPeriph_Lib_V3.5.0/Libraries/CMSIS/CM3/DeviceSupport/ST/STM32F10x/startup/gcc_ride7 \
bsp/boards/iot-lab_M3/library/STM32F10x_StdPeriph_Lib_V3.5.0/Libraries/CMSIS/CM3/DeviceSupport/ST/STM32F10x/startup/arm \
bsp/boards/iot-lab_M3/library/STM32F10x_StdPeriph_Lib_V3.5.0/Libraries/CMSIS/CM3/DeviceSupport/ST/STM32F10x/startup/TrueSTUDIO \
bsp/boards/iot-lab_M3/library/STM32F10x_StdPeriph_Lib_V3.5.0/Libraries/CMSIS/CM3/CoreSupport \
bsp/boards/iot-lab_M3/configure \
bsp/boards/gina \
bsp/boards/ez430-rf2500 \
bsp/boards/eldorado \
bsp/boards/derfmega \
bsp/boards/common \
bsp/boards/cc2538em \
bsp/boards/cc2538em/source \
bsp/boards/cc2538em/osens_itf \
bsp/boards/agilefox \
bsp/boards/agilefox/library/src \
bsp/boards/agilefox/ewarm \
bsp/boards/agilefox/configure \
bsp/boards/OpenMote-CC2538 \
bsp/boards/OpenMote-CC2538/source \
bootloader/k20 \
bootloader/k20/usb \
bootloader/k20/startup \
bootloader/k20/disk_flash_utils \
bootloader/k20/bootloader \

